### ISSUE TITLE
rake spree:i18n:refresh creates junk yaml file in locale dir

### ISSUE THREAD

**Issue by roja** [railsdog/spree-i18n#1]
running rake spree:i18n:refresh causes a yaml file to be created in the locales directory which contains a html 404 error message from github. This is caused by the following bit of code from translation.rake

```
task :refresh do
  puts "Fetching latest Spree locale file to #{language_root}"
  exec %(
    curl -Lo '#{language_root}/en_spree.yml' http://github.com/railsdog/spree/tree/master/config/locales/en_spree.yml?raw=true
  )      
end
```

this of course causes all the rake tasks to fail on the extension.

**Comment by roja** [comment]
the correct url should be for the raw file:

http://github.com/railsdog/spree/raw/master/config/locales/en_spree.yml

**Comment by romul** [comment]
Yup, looks like github changed URL format.

**Comment by romul** [comment]
Thank you for contributing.
